DROP SCHEMA IF EXISTS account;
DROP SCHEMA IF EXISTS core;
DROP SCHEMA IF EXISTS classrooms;
DROP SCHEMA IF EXISTS meal;
DROP SCHEMA IF EXISTS payments;
DROP SCHEMA IF EXISTS receivables;
DROP SCHEMA IF EXISTS finances;
COMMIT;